### PR TITLE
Feature: Substance

### PR DESCRIPTION
**Pull request by devboy**
DataStructures!!! DataStructures!!! DataStructures!!!

This integrates a library (temporarily) called Substance (https://github.com/devboy/Substance), where I took Microsofts latest .NET data-structures from
https://github.com/dotnet/corefx & https://github.com/dotnet/coreclr, and patched them a bit so they play nicely with Unity.

The namespaces are still preserved (`System.Collections.Immutable` etc.), which makes it possible to progressively integrate/port more libraries into the Substance project. 

So far it's just data-structures:
- `System.Collections`
- `System.Collections.Generic`
- `System.Collections.Immutable`

But there is plenty of potentially useful stuff in there like Threading.Task,Collections.Concurrent,Crypto,Cache,FileIO,NetworkIO and much much more.

Example:

```
using UnityEngine;
using System.Collections;
using System.Collections.Immutable;
using System.Net;
using System.Net.Cache;
using System;
using Wooga.Lambda.Network;
using Wooga.Lambda.Network.Transport;

public class Test1 : MonoBehaviour {
	
	// Use this for initialization
	void Start () {
		Debug.Log (Tuple.Create<string,int>("a",1));
		Debug.Log (ImmutableArray.Create("a","b","c"));
		Debug.Log (ImmutableList.Create(1,2,3,4));
		Debug.Log (ImmutableQueue.Create("a","a"));
		Debug.Log (WebRequestTransport.CreateHttpClient().Get("http://google.com").Body);
	}
	
	// Update is called once per frame
	void Update () {
	
	}
}

```

### CODE REVIEW

**Comment by arne-schroppe** [comment]
[] Remove aliases from Seq
[] Remove File and Location from IO.FileSystem
[] Replace FileSystem.GetFileAsync with FileSystem.ReadAsync (returning an IEnumerable)
[] Reimplement VirtualFileSystem
[] Fix all libraries that use these APIs
[] Evaluate Wooga.Networking (How does it feel to use this with the file api?)

**Comment by flowsprenger** [comment]
[ ] make substance.immutable run with .net 2 subset

**Comment by otso** [comment]
Considering giving a  short preso at least for our team about the new stuff usable?

**Comment by flowsprenger** [comment]
i will consider looking at networking done for now. i think we need to do that again as soon as we actually start using it (in coreservices).

**Pull request merged**
